#!/bin/bash
SCRIPT="${0}"
SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)

set -m
DB_BASENAME="wordland_test_"
DATABASE_COUNT="$(echo "select datname from pg_database" | psql -qt -U postgres | grep ${DB_BASENAME} | wc -l | tr -d ' ')"

if [ ${DATABASE_COUNT} -gt 0 ] ; then
  echo "Cleaning up ${DATABASE_COUNT} databases..."

  DATABASES="$(echo "select datname from pg_database" | psql -qt -U postgres | grep ${DB_BASENAME} | tr -d ' ')"
  if [ ! -z "${DATABASES}" ] ; then
    for db in ${DATABASES} ; do
      dropdb -U postgres ${db} &
    done
  fi
else
  echo "No databases with basename \"${DB_BASENAME}\" to clean up"
fi
