#!/bin/bash

SCRIPT="${0}"
SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)

MODELS_DIR=$(cd ${SCRIPT_DIR}/../src/main/resources/models/rooms && pwd)

for model in $(ls -1 ${MODELS_DIR}) ; do
  wl_model rooms/${model}
done
