#!/bin/bash

SCRIPT="${0}"
SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
. ${SCRIPT_DIR}/_wl_common

ROOM_NAME="${1:?$(translate_message err_room_required)}"
WEBSOCKET_PID="${2:?$(translate_message err_websocket_wl_play_pid_required)}"

ROOM_DIR=$(room_dir ${ROOM_NAME})
WEBSOCKET_FILE="$(room_web_socket "${ROOM_NAME}")"
ROOM_API="${WL_API}/rooms/${ROOM_NAME}"

ACTIVE_CHAR=""
ACTIVE_CHAR_INDEX=1
ACTIVE_TRAY_INDEX=1
TILES=()
LETTERS=()
INDEXES=()

function reset_play {
  unset TILES
  TILES=()
  unset LETTERS
  LETTERS=()
  unset INDEXES
  INDEXES=()
  ACTIVE_CHAR=""
  ACTIVE_CHAR_INDEX=1
  ACTIVE_TRAY_INDEX=1
}

function current_word {
  for c in "${LETTERS[@]}" ; do
    echo -n "${c}" | tr '[:lower:]' '[:upper:]'
  done
}
function current_word_length {
  echo -n $(current_word) | wc -c | tr -d ' '
}

function subtract_letter {
  if [[ -z "$(current_word)" ]] ; then
    return
  fi

  LETTER_INDEX=$(expr ${ACTIVE_TRAY_INDEX} - 1)
  if [[ ${LETTER_INDEX} -lt 0 ]] ; then
    # should never happen
    return
  fi
  if [[ ${ACTIVE_TRAY_INDEX} -le 0 ]] ; then
    ACTIVE_TRAY_INDEX=1
  fi

  # debug "start subtract_letter: letters=${LETTERS[@]} / LETTER_INDEX=${LETTER_INDEX}, ACTIVE_TRAY_INDEX=${ACTIVE_TRAY_INDEX}"

  unset 'TILES[${LETTER_INDEX}]'
  unset 'LETTERS[${LETTER_INDEX}]'
  unset 'INDEXES[${LETTER_INDEX}]'
  TILES=( "${TILES[@]:0:${LETTER_INDEX}}" "${TILES[@]:${LETTER_INDEX}}" )
  LETTERS=( "${LETTERS[@]:0:${LETTER_INDEX}}" "${LETTERS[@]:${LETTER_INDEX}}" )
  INDEXES=( "${INDEXES[@]:0:${LETTER_INDEX}}" "${INDEXES[@]:${LE}}" )

#  ACTIVE_CHAR="$(echo $(current_word) | head -c $(expr ${ACTIVE_CHAR_INDEX} + 1) | tail -c 1)"
  ACTIVE_CHAR="${LETTERS[${LETTER_INDEX}]}"
  ACTIVE_CHAR_INDEX="${INDEXES[${LETTER_INDEX}]}"
  # debug "end subtract_letter: letters=${LETTERS[@]} / LETTER_INDEX=${LETTER_INDEX}, ACTIVE_TRAY_INDEX=${ACTIVE_TRAY_INDEX}, AC=${ACTIVE_CHAR}, should be ${LETTERS[${LETTER_INDEX}]}, L0=${LETTERS[0]}, L1=${LETTERS[1]}, L2=${LETTERS[2]}"
}

function play_obj {
  if [[ ! -z ${CURRENT_PLAY} && ${#LETTERS[@]} -gt 0 ]] ; then
    cat <<EOF
  {
    "room": "${ROOM_NAME}",
    "stateChange": "word_played",
    "id": "$(session_player)",
    "clientId": "$(session_player)",
    "apiToken": "$(session_apiToken)",
    "word": "$(current_word)",
    "tiles": ${CURRENT_PLAY}
  }
EOF
  else
    error "no valid word to play"
  fi
}

X1=$(cat ${ROOM_DIR}/x1)
Y1=$(cat ${ROOM_DIR}/y1)
VIEW_SIZE=$(cat ${ROOM_DIR}/view_size)
ROOM_PALETTE=${ROOM_DIR}/palette.json
BOARD_JSON=${ROOM_DIR}/board.json
PLAY_JSON=${ROOM_DIR}/play.json

BOARD_REQUEST_PREFIX="{ \"palette\": "
BOARD_REQUEST_TILES_JSON_PREFIX=", \"tiles\": [ "
BOARD_REQUEST_TILES_JSON_SEP=", "
BOARD_REQUEST_JSON_SUFFIX=" ] }"

function board_preview_obj {
  echo -n "${BOARD_REQUEST_PREFIX}"
  if [[ -f ${ROOM_PALETTE} && $(cat ${ROOM_PALETTE} | tr -d ' \n' | wc -c | tr -d ' ') -gt 0 ]] ; then
    cat ${ROOM_PALETTE}
  else
    echo -n "null"
  fi
  echo -n "${BOARD_REQUEST_TILES_JSON_PREFIX}"
  first=1
  for tile in "${TILES[@]}" ; do
    if [[ "${tile}" =~ /null/ ]] ; then
      break
    fi
    if [[ -z "$(echo -n ${tile} | tr -d ' ')" ]] ; then
      continue
    fi
    if [ ${first} -ne 1 ] ; then
      echo -n "${BOARD_REQUEST_TILES_JSON_SEP}"
    fi
    echo -n " { ${tile} }"
    first=0
  done
  echo -n "${BOARD_REQUEST_JSON_SUFFIX}"
}

function save_room_state {
  PALETTE="$(json_node "$(cat ${BOARD_JSON})" palette)"
  if [[ ! -z "${PALETTE}" ]] ; then
    echo "${PALETTE}" > ${ROOM_PALETTE}
  fi
  X1="$(json_val "$(cat ${BOARD_JSON})" x1)"
  X2="$(json_val "$(cat ${BOARD_JSON})" x2)"
  Y1="$(json_val "$(cat ${BOARD_JSON})" y1)"
  Y2="$(json_val "$(cat ${BOARD_JSON})" y2)"
  if [[ ! -z "${X1}" ]] ; then echo "${X1}" > ${ROOM_DIR}/x1 ; fi
  if [[ ! -z "${X2}" ]] ; then echo "${X2}" > ${ROOM_DIR}/x2 ; fi
  if [[ ! -z "${Y1}" ]] ; then echo "${Y1}" > ${ROOM_DIR}/y1 ; fi
  if [[ ! -z "${Y2}" ]] ; then echo "${Y2}" > ${ROOM_DIR}/y2 ; fi
}

function show_tray {
  echo
  if [[ -z "$(current_word)" ]] ; then
    echo "   [  (empty)  ]"
    echo
  else
    echo "   [  $(current_word)  ]"
    echo -n "     "
    i=0
    while [[ ${i} -lt ${ACTIVE_TRAY_INDEX} ]] ; do
      echo -n " "
      i=$(expr ${i} + 1)
    done
    echo "^"
  fi
}

function show_board {
  if [[ -f ${BOARD_JSON} ]] ; then
    cp ${BOARD_JSON} ${BOARD_JSON}.bak
  fi
  # debug $(echo "> end: BPO: $(board_preview_obj)" | grep tiles)
  board_status="$(wl_post "${ROOM_API}/board/preview.txt?x1=${X1}&x2=$(expr ${X1} + ${VIEW_SIZE})&y1=${Y1}&y2=$(expr ${Y1} + ${VIEW_SIZE})" "$(board_preview_obj)" "${BOARD_JSON}" "200 422")" \
    || die "$(translate_message err_api_boardView)"
  case $(http_code ${board_status}) in
    200)
      board="$(json_node "$(cat ${BOARD_JSON})" grid)"
      if [[ ! -z "${board}" ]] ; then
        save_room_state
        roomState="$(json_val "$(cat ${BOARD_JSON})" roomState)"
        if [[ ! -z "${roomState}" && "${roomState}" == "ended" ]] ; then
          echo "$(translate_message msg_game_over)"
          winners="$(cat ${BOARD_JSON} | jq -c '.scoreboard[] | select(.winner) | .name' | tr -d '"')"
          if [[ $(echo "${winners}" | wc -l) -gt 1 ]] ; then
            echo "$(translate_message label_winners): ${winners}"
          else
            echo "$(translate_message label_winner): ${winners}"
          fi
        fi
        echo
        printf "$(printf "${board}" | tr -d '"')"
      fi
    ;;
    422)
      error "$(validation_errors "${BOARD_JSON}")"
      if [[ -f ${BOARD_JSON}.bak ]] ; then
        cp ${BOARD_JSON}.bak ${BOARD_JSON}
      fi
    ;;
    *)
      die "$(translate_message err_api_boardView)"
    ;;
  esac

  if [[ ${#TILES[*]} -gt 0 ]] ; then
    SUCCESS="$(json_val "$(cat ${BOARD_JSON})" success)"
    if [[ -z "${SUCCESS}" || "${SUCCESS}" != "true" ]] ; then
      error -n "$(translate_message 'err_game_invalidPlay'): $(current_word)"
      CURRENT_PLAY=""
    else
      CURRENT_PLAY="$(json_node "$(cat ${BOARD_JSON})" playedTiles)"
    fi
  fi
}

function player_name {
  player_info=$(wl_get "${ROOM_API}/players/${1}")
  if [[ ! -z "${player_info}" ]] ; then
    echo -n "$(json_val "${player_info}" name)"
  fi
}

function abandon_game {

  echo ; echo ; echo -n "$(translate_message msg_confirm_abandon_game) "
  IFS= read -s -r -n1 char 2> /dev/null
  if [[ $(is_yes "${char}") != "true" ]] ; then
    return
  fi

  LEAVE_JSON=$(mktemp /tmp/$(basename $0).abandon_game.XXXXXXXX.json)
  leave_status="$(wl_post "${ROOM_API}/abandon" "{}" "${LEAVE_JSON}" "200 422")"
  LEAVE_JSON="$(cat "${LEAVE_JSON}")"
  rm -f ${LEAVE_JSON}

  case $(http_code ${leave_status}) in
    200)
      echo ; echo ; echo "$(translate_message msg_game_abandoned)" ; echo
      exec ${SCRIPT_DIR}/wl_rooms
    ;;
    422)
      echo ; echo ; die $(validation_errors "${LEAVE_JSON}")
    ;;
    *)
      echo ; echo ; die "$(translate_message err_api_play)"
    ;;
  esac
}

function fresh_board_view {
  show_board ; echo ; show_tray
  if [[ ! -z "${1}" ]] ; then
    echo -n "${1}"
  else
    echo -n "$(wl_prompt)"
  fi
}

function async_fresh_board_view {
  ANY_PRINTOUTS=0
  while read line ; do
    change="$(json_val "${line}" stateChange)"
    case ${change} in
      player_joined|player_joined_game_started)
        if [[ ${ANY_PRINTOUTS} -eq 0 ]] ; then echo ; echo ; fi
        echo "$(json_val "${line}" object.name) $(translate_message msg_has_joined_the_game)"
        ANY_PRINTOUTS=1
        ;;
      player_left|player_left_game_ended)
      if [[ ${ANY_PRINTOUTS} -eq 0 ]] ; then echo ; echo ; fi
        echo "$(player_name $(json_val "${line}" object)) $(translate_message msg_has_abandoned_the_game)"
        ANY_PRINTOUTS=1
        ;;
      word_played|word_played_game_ended)
        playerId="$(json_val "${line}" object.id)"
        if [[ ! -z "${playerId}" && "${playerId}" == "$(session_player)" ]] ; then
          : # if this was ourselves, don't print anything
        else
          if [[ ${ANY_PRINTOUTS} -eq 0 ]] ; then echo ; echo ; fi
          echo "$(json_val "${line}" player.name) $(translate_message msg_played_word) $(json_val "${line}" object.word)"
          ANY_PRINTOUTS=1
        fi
        ;;
      *)
        echo "unrecognized async update (${change}) ~~~~  : ${line}"
        ;;
    esac
    if [[ ${change} =~ /_game_ended/ ]] ; then
      if [[ ${ANY_PRINTOUTS} -eq 0 ]] ; then echo ; echo ; fi
      echo "Game Over"
      ANY_PRINTOUTS=1
    fi
  done < ${1}
  if [[ ${ANY_PRINTOUTS} -eq 1 ]] ; then
    echo ; fresh_board_view
  fi
}

function show_rooms {
  rooms_json=$(wl_get ${WL_API}/me/rooms)
  i=1
  #echo "${rooms_json}" >> /tmp/rooms.json
  for room in $(echo "${rooms_json}" | jq '.[] | .name' | tr -d '"') ; do
    roomState=$(json_find "${rooms_json}" name "${room}" roomState)
    echo "${i} - ${room} - $(translate_message msg_room_state_${roomState})"
    i=$(expr ${i} + 1)
  done
  echo "n - New Game"
  echo "q - Back to Current Game"
  echo ; echo -n "$(room_prompt)"
  while IFS= read line 2> /dev/null ; do
    if [[ ! -z "${line}" ]] ; then
      case ${line} in
        q|Q)
          return
        ;;
        n|N)
          echo ; echo ; exec ${SCRIPT_DIR}/wl_rooms
        ;;
        (*[!0-9]*)
          echo ; echo -n "$(room_prompt)"
          continue
        ;;
        *)
          # all digits, must be room number
          line=$(echo "${line}" | tr -d ' \n')
          if [[ -z "${line}" ]] ; then
            break
          fi
          roomName=$(echo "${rooms_json}" | jq '.['$(expr ${line} - 1)'] | .name' | tr -d '"')
          if [[ $(wl_exists "${WL_API}/rooms/${roomName}") == "true" ]] ; then
            exec ${SCRIPT_DIR}/wl_join "${roomName}"
          else
            error "$(translate_message err_room_notFound)"
          fi
        ;;
      esac
    fi
    echo ; echo -n "$(room_prompt)"
  done
  echo "end of script" >> /tmp/roomlog
}

function show_plays {
  plays_json=$(wl_get "${ROOM_API}/plays")
  if [[ ! -z "${plays_json}" ]] ; then
    while read play ; do
#      echo "saw this play: ${play}, by $(echo "${play}" | jq .player.name)"
      echo "$(json_val "${play}" player.name) $(translate_message msg_played_word) $(json_val "${play}" word)"
      if [[ ! -z "${1}" && "${1}" == "in_detail" ]] ; then
        while read score ; do
          scoreType="$(json_val "${score}" type)"
          if [[ -z "${scoreType}" ]] ; then
            continue
          fi
          echo -n "  $(translate_message msg_play_detail_score_${scoreType})"
          case ${scoreType} in
            symbol)
              echo "$(json_val ${score} info.symbol) @ $(json_val ${score} info.x)x$(json_val ${score} info.y): $(json_val ${score} picas) $(translate_message label_picas)"
            ;;
            word)
              echo "$(json_val ${score} info.word): $(json_val ${score} picas) $(translate_message label_picas)"
            ;;
            board)
              echo "$(json_val ${score} info.name): $(json_val ${score} picas) $(translate_message label_picas)"
            ;;
          esac

        done <<<"$(echo "${play}" | jq -c '.score.scores[]')"
      fi
      if [[ ! -z "${1}" && "${1}" == "in_detail" ]] ; then
        echo
      fi
    done <<<"$(echo "${plays_json}" | jq -c '.[]')"
  fi
}

function move_board_prompt {
  echo -n "$(translate_message msg_move_board_prompt)>>> "
}

function move_board {
  # debug "move_board: starting with x1=${X1}, y1=${Y1}"
  echo ; echo -n "$(move_board_prompt)"
  while [ 1 ] ; do
    while IFS= read -s -r -t 2 -n1 char 2> /dev/null ; do
      case ${char} in
        q|Q)
          echo ; return
        ;;
        '?')
          lang_file "move_board"
          echo ; echo -n "$(move_board_prompt)"
          continue
        ;;
        w|W)
          # echo "move_board: moving up (W)"
          X1=$(expr ${X1} - 1)
        ;;
        a|A)
          # echo "move_board: moving left (A)"
          Y1=$(expr ${Y1} - 1)
        ;;
        s|S)
          # echo "move_board: moving down (S)"
          X1=$(expr ${X1} + 1)
        ;;
        d|D)
          # echo "move_board: moving right (D)"
          Y1=$(expr ${Y1} + 1)
        ;;
        *)
          continue
        ;;
      esac
      # debug "move_board: ending with x1=${X1}, y1=${Y1}"
      echo "${X1}" > ${ROOM_DIR}/x1
      echo "${Y1}" > ${ROOM_DIR}/y1
      reset_play
      fresh_board_view "$(move_board_prompt)"
    done
  done
}

function board_image {
  # todo: send X1/X2/Y1/Y2 that are all equally larger than the current screen view
  board_view_png="$(wl_get ${ROOM_API}/board/view.png)"
  png_file="$(mktemp /tmp/$(basename ${0}).XXXXXXXX.png)"
  json_val "${board_view_png}" base64image | base64 -d > ${png_file}
  IMAGE_VIEWER="$(image_viewer)"
  if [[ -z "${IMAGE_VIEWER}" ]] ; then
    error "$(translate_message err_imageViewer_notFound): ${png_file}"
  else
    set -m
    ${IMAGE_VIEWER} ${png_file} &
  fi
}

fresh_board_view

while [ 1 ] ; do
 while IFS= read -s -r -t 2 -n1 char 2> /dev/null ; do
  reset=0
  case ${char} in
    # Add a letter to the tray
    [a-zA-z])
      ACTIVE_CHAR="${char}"
      ACTIVE_CHAR_INDEX=1

      existing=()
      i=0
      while [[ ${i} -lt $(current_word_length) ]] ; do
        c="${LETTERS[${i}]}"
        if [[ ${c} == ${char} ]] ; then
          existing+=( ${INDEXES[${i}]} )
        fi
        i=$(expr ${i} + 1)
      done
      # debug "found existing=${existing}"
      i=1
      correctIndex=""
      while [[ -z "${correctIndex}" ]] ; do
        if [[ $(printf '%s\n' "${existing[@]}" | grep ${i} | wc -l | tr -d ' ') -eq 0 ]] ; then
          correctIndex=${i}
        fi
        i=$(expr ${i} + 1)
      done
      if [[ ! -z ${correctIndex} ]] ; then
        ACTIVE_CHAR_INDEX=${correctIndex}
        # debug "AZ: correctIndex=${correctIndex}, CWL=$(current_word_length), ATI=${ACTIVE_TRAY_INDEX}"
        if [[ ${#TILES[@]} -gt 0 && ${ACTIVE_TRAY_INDEX} -lt $(current_word_length) ]] ; then
          # shift all other elements forward to make room for new one
          i=${#TILES[@]}
          TILES+=("${TILES[$(expr ${i}-1)]]}")
          LETTERS+=("${LETTERS[$(expr ${i}-1)]]}")
          INDEXES+=("${INDEXES[$(expr ${i}-1)]]}")
          while [[ ${i} -ge ${ACTIVE_TRAY_INDEX} ]] ; do
            TILES[${i}]="${TILES[$(expr ${i}-1)]}"
            LETTERS[${i}]="${LETTERS[$(expr ${i}-1)]}"
            INDEXES[${i}]="${INDEXES[$(expr ${i}-1)]}"
            i=$(expr ${i} - 1)
          done
          # debug "AZ: adding letter in middle: ${ACTIVE_TRAY_INDEX}"
          TILES[${ACTIVE_TRAY_INDEX}-1]="\"symbol\": \"${char}\", \"index\": ${ACTIVE_CHAR_INDEX}"
          LETTERS[${ACTIVE_TRAY_INDEX}-1]="${char}"
          INDEXES[${ACTIVE_TRAY_INDEX}-1]=${ACTIVE_CHAR_INDEX}
        else
          # add element at the end
          # debug "AZ: adding letter at end"
          TILES+=("\"symbol\": \"${char}\", \"index\": ${ACTIVE_CHAR_INDEX}")
          LETTERS+=("${char}")
          INDEXES+=(${ACTIVE_CHAR_INDEX})
          ACTIVE_TRAY_INDEX=$(expr ${ACTIVE_TRAY_INDEX} + 1)
        fi
        if [[ ${ACTIVE_TRAY_INDEX} -ge $(current_word_length) ]] ; then
          ACTIVE_TRAY_INDEX=$(current_word_length)
        fi
      else
        continue
      fi
    ;;

    # Increment current active char index
    '>')
      # debug "> start: ATI=${ACTIVE_TRAY_INDEX}, AC=${ACTIVE_CHAR}, ACI=${ACTIVE_CHAR_INDEX}, #TILES[@]=${#TILES[@]}"
      if [[ ${#TILES[@]} -gt 0 ]] ; then
        existing=()
        i=0
        while [[ ${i} -lt $(current_word_length) ]] ; do
          c="${LETTERS[${i}]}"
          if [[ ${c} == ${ACTIVE_CHAR} ]] ; then
            existing+=( ${INDEXES[${i}]} )
          fi
          i=$(expr ${i} + 1)
        done

        ACTIVE_CHAR_INDEX=$(expr ${ACTIVE_CHAR_INDEX} + 1)
        # debug "> found existing=${existing}"
        i=${ACTIVE_CHAR_INDEX}
        correctIndex=""
        while [[ -z "${correctIndex}" ]] ; do
          if [[ $(printf '%s\n' "${existing[@]}" | grep ${i} | wc -l | tr -d ' ') -eq 0 ]] ; then
            correctIndex=${i}
            break
          fi
          i=$(expr ${i} + 1)
        done
        # debug "> found correctIndex=${correctIndex}"
        if [[ ! -z ${correctIndex} ]] ; then
          ACTIVE_CHAR_INDEX=${correctIndex}
          TILES[${ACTIVE_TRAY_INDEX}-1]="\"symbol\": \"${LETTERS[${ACTIVE_TRAY_INDEX}-1]}\", \"index\": ${ACTIVE_CHAR_INDEX}"
          INDEXES[${ACTIVE_TRAY_INDEX}-1]=${ACTIVE_CHAR_INDEX}
          # debug $(echo "> end: BPO: $(board_preview_obj)" | grep tiles)
        else
          continue
        fi
      else
        continue
      fi
    ;;

    # Decrement current active char index, if possible
    '<')
      # debug "< start: ATI=${ACTIVE_TRAY_INDEX}, AC=${ACTIVE_CHAR}, ACI=${ACTIVE_CHAR_INDEX}, #TILES[@]=${#TILES[@]}"
      if [[ ${#TILES[@]} -gt 0 ]] ; then
        ACTIVE_CHAR_INDEX=$(expr ${ACTIVE_CHAR_INDEX} - 1)
        if [ ${ACTIVE_CHAR_INDEX} -lt 1 ] ; then
          ACTIVE_CHAR_INDEX=1
        else
          # what is the first available index that is less than the current index?
          existing=()
          i=0
          while [[ ${i} -lt $(current_word_length) ]] ; do
            c="${LETTERS[${i}]}"
            # debug "< comparing letter ${c} to play ${ACTIVE_CHAR}"
            if [[ ${c} == ${ACTIVE_CHAR} ]] ; then
              existing+=( ${INDEXES[${i}]} )
            fi
            i=$(expr ${i} + 1)
          done
          # debug "< found existing=${existing}"
          i=${ACTIVE_CHAR_INDEX}
          correctIndex=""
          while [[ ${i} -gt 0 ]] ; do
            found=0
            if [[ $(printf '%s\n' "${existing[@]}" | grep ${i} | wc -l | tr -d ' ') -eq 0 ]] ; then
              correctIndex=${i}
              break
            fi
            i=$(expr ${i} - 1)
          done
          # debug "< found correctIndex=${correctIndex}"
          if [[ -z ${correctIndex} ]] ; then
            return
          fi
          ACTIVE_CHAR_INDEX=${correctIndex}

          TILES[${ACTIVE_TRAY_INDEX}-1]="\"symbol\": \"${LETTERS[${ACTIVE_TRAY_INDEX}-1]}\", \"index\": ${ACTIVE_CHAR_INDEX}"
          INDEXES[${ACTIVE_TRAY_INDEX}-1]=${ACTIVE_CHAR_INDEX}
        fi
        # debug "< end : ATI=${ACTIVE_TRAY_INDEX}, AC=${ACTIVE_CHAR}, ACI=${ACTIVE_CHAR_INDEX}, #TILES[@]=${#TILES[@]}"
        # debug $(echo "> end: BPO: $(board_preview_obj)" | grep tiles)
      else
        continue
      fi
    ;;

    # Move current letter to the right in the tray, if possible
    ']')
      if [[ ${#TILES[@]} -gt 1 && ${ACTIVE_TRAY_INDEX} -lt $(current_word_length) ]] ; then
        ATR_INDEX=$(expr ${ACTIVE_TRAY_INDEX} - 1)
        next=$(expr ${ATR_INDEX} + 1)
        SAVED_TILE="${TILES[${next}]}"
        SAVED_LETTER="${LETTERS[${next}]}"
        SAVED_INDEX="${INDEXES[${next}]}"
        TILES[${next}]="${TILES[${ATR_INDEX}]}"
        LETTERS[${next}]="${LETTERS[${ATR_INDEX}]}"
        INDEXES[${next}]="${INDEXES[${ATR_INDEX}]}"
        TILES[${ATR_INDEX}]="${SAVED_TILE}"
        LETTERS[${ATR_INDEX}]="${SAVED_LETTER}"
        INDEXES[${ATR_INDEX}]="${SAVED_INDEX}"
        ACTIVE_TRAY_INDEX=$(expr ${ACTIVE_TRAY_INDEX} + 1)
      else
        continue
      fi
    ;;

    # Move current letter to the left in the tray, if possible
    '[')
      if [[ ${#TILES[@]} -gt 1 && ${ACTIVE_TRAY_INDEX} -gt 1 ]] ; then
        ATR_INDEX=$(expr ${ACTIVE_TRAY_INDEX} - 1)
        prev=$(expr ${ATR_INDEX} - 1)
        SAVED_TILE="${TILES[${prev}]}"
        SAVED_LETTER="${LETTERS[${prev}]}"
        SAVED_INDEX="${INDEXES[${prev}]}"
        TILES[${prev}]="${TILES[${ATR_INDEX}]}"
        LETTERS[${prev}]="${LETTERS[${ATR_INDEX}]}"
        INDEXES[${prev}]="${INDEXES[${ATR_INDEX}]}"
        TILES[${ATR_INDEX}]="${SAVED_TILE}"
        LETTERS[${ATR_INDEX}]="${SAVED_LETTER}"
        INDEXES[${ATR_INDEX}]="${SAVED_INDEX}"
        ACTIVE_TRAY_INDEX=$(expr ${ACTIVE_TRAY_INDEX} - 1)
      else
        continue
      fi
    ;;

    # Change currently active letter in the tray to the right, if possible
    '}')
      if [[ ${#TILES[@]} -gt 1 && ${ACTIVE_TRAY_INDEX} -lt $(current_word_length) ]] ; then
        ATR_INDEX=$(expr ${ACTIVE_TRAY_INDEX})
        next=$(expr ${ATR_INDEX} + 1)
        ACTIVE_TRAY_INDEX=${next}
        ACTIVE_CHAR="${LETTERS[${ATR_INDEX}]}"
        ACTIVE_CHAR_INDEX="${INDEXES[${ATR_INDEX}]}"
        # debug "} end: ATI=${ACTIVE_TRAY_INDEX}, AC=${ACTIVE_CHAR}, ACI=${ACTIVE_CHAR_INDEX}, #TILES[@]=${#TILES[@]}"
      else
        continue
      fi
    ;;

    # Change currently active letter in the tray to the left, if possible
    '{')
      if [[ ${#TILES[@]} -gt 1 && ${ACTIVE_TRAY_INDEX} -gt 1 ]] ; then
        ATR_INDEX=$(expr ${ACTIVE_TRAY_INDEX} - 1)
        prev=$(expr ${ATR_INDEX} - 1)
        ACTIVE_TRAY_INDEX=${ATR_INDEX}
        ACTIVE_CHAR="${LETTERS[${prev}]}"
        ACTIVE_CHAR_INDEX="${INDEXES[${prev}]}"
        # debug "{ end: ATI=${ACTIVE_TRAY_INDEX}, AC=${ACTIVE_CHAR}, ACI=${ACTIVE_CHAR_INDEX}, #TILES[@]=${#TILES[@]}"
      else
        continue
      fi
    ;;

    # Submit the letters in the tray as our play, if there are any
    '')
      if [[ -z "${CURRENT_PLAY}" ]] ; then
        error "$(translate_message err_game_noCurrentPlay)"
      else
        play_status="$(wl_post "${ROOM_API}/play" "$(play_obj)" "${PLAY_JSON}" "200 422")"
        case $(http_code ${play_status}) in
          200)
            reset_play
            reset=1
            play_output=""
          ;;
          422)
            play_output="$(validation_errors "$(cat "${PLAY_JSON}")")"
          ;;
          *)
            play_output="$(translate_message err_api_play)"
          ;;
        esac
      fi
    ;;

    # Remove the most recently added letter from the tray
    '-')
      subtract_letter
    ;;

    # Clear the tray
    ' ')
      echo ; echo "$(translate_message msg_word_reset)"
      reset_play
      reset=1
    ;;

    '?')
      lang_file "help"
    ;;

    '1')
      echo ; echo
      show_plays
    ;;

    '!')
      echo ; echo
      show_plays in_detail
    ;;

    '~')
      echo ; echo
      move_board
    ;;

    '@')
      echo ; echo
      board_image
    ;;

    # Didn't understand that, skip it
    '^')
      abandon_game
      ;;
    *)
      continue
    ;;
  esac

  # Get the board preview
  if [[ ${reset} -eq 1 ]] ; then
    reset=0
  fi
  show_board

  # If the play resulted in a message to the user, show that here
  if [[ ! -z "${play_output}" ]] ; then
    error -n "${play_output}"
    play_output=""
  fi

  # Show the tray
  echo
  show_tray

  echo -n "$(wl_prompt)"

 done

 if [[ -f ${WEBSOCKET_FILE} ]] ; then
   WS_TEMP=${WEBSOCKET_FILE}.$(date +%s).$(uuid | head -c 8).json
   mv ${WEBSOCKET_FILE} ${WS_TEMP}
   async_fresh_board_view ${WS_TEMP}
   rm -f ${WS_TEMP}
 fi
done
