#!/bin/bash

SCRIPT="${0}"
SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
. ${SCRIPT_DIR}/_wl_base

WL_PLAY_PID=${1:?$(translate_message err_websocket_no_wl_play_pid)}
WL_SOCKET_PID=$$
echo ">>> $0 started with pid ${WL_SOCKET_PID}"
WEBSOCKET_PAYLOAD=${WL_DIR}/_websocket

function join_obj {
  cat | tr -d '\n' <<EOF
{
 "id": "$(session_player)",
 "clientId": "$(session_player)",
 "apiToken":"$(session_apiToken)",
 "room":"$(current_room)",
 "stateChange":"player_joined"
}
EOF
}

echo "$(join_obj)" | websocat -n ${DEFAULT_WS_API}/$(session_player) | {
  cat /dev/null > ${WEBSOCKET_PAYLOAD}
  while read line ; do
  echo "${line}" >> ${WEBSOCKET_PAYLOAD}
    if [[ ! -z "${line}" && "$(echo "${line}" | tr -d ' \n')" != "X" ]] ; then
      mkdir -p ${WS_MARKER_FILE_DIR} && touch ${WS_MARKER_FILE_DIR}/${WL_PLAY_PID}
    fi
  done
}
