#!/bin/bash

SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
. ${SCRIPT_DIR}/_wl_base

function wl_auth {
  USERNAME="${1}"
  ASK_TO_SIGNUP="${2:-Y}"
  OPTIONAL=""
  if [[ ${ASK_TO_SIGNUP} == "Y" || ${ASK_TO_SIGNUP} == "y" ]] ; then
    OPTIONAL=" (optional)"
  fi

  if [[ -z "${USERNAME}" || ( ${ASK_TO_SIGNUP} == "Y" || ${ASK_TO_SIGNUP} == "y" ) ]] ; then

    response=$(curl --silent --write-out "\n%{http_code}\n" ${WL_API}/auth)
    status_code=$(echo "$response" | sed -n '$p')
    json=$(echo "$response" | sed '$d')

    if [ -z "${status_code}" ] ; then
      die "error checking session: ${json}"
    fi
    if [ ${status_code} -eq 200 ] ; then
      echo "${json}" > ${SESSION_JSON}
      return
    elif [[ ${status_code} -eq 404 || -z "${USERNAME}" ]] ; then
      echo -n "Username${OPTIONAL}: "
      read USERNAME
    else
      die "error checking status: ${status_code} / ${json}"
    fi
  fi
  if [[ -z "${USERNAME}" && ( -z "${ASK_TO_SIGNUP}" || ${ASK_TO_SIGNUP} == "N" || ${ASK_TO_SIGNUP} == "n" ) ]] ; then
    die "username is required"
  fi

  echo -n "Email${OPTIONAL}: "
  read EMAIL

  if [[ -z "${EMAIL}" && ( -z "${ASK_TO_SIGNUP}" || ${ASK_TO_SIGNUP} == "N" || ${ASK_TO_SIGNUP} == "n" ) ]] ; then
    die "email is required"
  fi

  if [[ ! -z "${EMAIL}" ]] ; then
    if [[ -z "${ASK_TO_SIGNUP}" || ${ASK_TO_SIGNUP} == "Y" ]] ; then
      echo -n "Sign up for an account? [Y/N] (enter Y if you already have an account, you'll be signed in) "
      read SIGN_UP
    else
      SIGN_UP="Y"
    fi
    if [[ ! -z "${SIGN_UP}" && ( "${SIGN_UP}" == "Y" || "${SIGN_UP}" == "y" ) ]] ; then
      # Yes, sign up for an account with email
      echo -n "Password: "
      read -s PASSWORD
      SECRETS=""
      if [ ! -z ${SKIP_CAPTCHA_SECRET} ] ; then
        SECRETS='{ "name": "'${SKIP_CAPTCHA_SECRET}'", "value": "'${SKIP_CAPTCHA_SECERT}'" }'
      fi
      response=$(curl --header "Content-Type: application/json" --silent --write-out "\n%{http_code}\n" -X POST -d '{"username": "'${USERNAME}'", "email": "'${EMAIL}'", "password": "'${PASSWORD}'", "secrets": [ '"${SECRETS}"' ]}' ${WL_API}/auth/register)
      status_code=$(echo "${response}" | sed -n '$p')
      json=$(echo "${response}" | sed '$d')
      if [[ ${status_code} -ne 200 ]] ; then
        die "Error signing up: ${json}"
      fi
      echo "${json}" > ${SESSION_JSON}

    else
      # No don't sign up, use anonymous account with email
      response=$(curl --header "Content-Type: application/json" --silent --write-out "\n%{http_code}\n" -X POST -d '{"username": "'${USERNAME}'", "email": "'${EMAIL}'"}' ${WL_API}/auth/register)
      status_code=$(echo "${response}" | sed -n '$p')
      json=$(echo "${response}" | sed '$d')
      if [[ ${status_code} -ne 200 ]] ; then
        die "Error logging in: ${status_code} / ${json}"
      fi
      echo "${json}" > ${SESSION_JSON}
    fi
  else
    # Can't sign up without email, use anonymous account with username, or no username (one will be assigned)
    response=$(curl --header "Content-Type: application/json" --silent --write-out "\n%{http_code}\n" -X POST -d '{"name": "'${USERNAME}'"}' ${WL_API}/auth/login)
    status_code=$(echo "${response}" | sed -n '$p')
    json=$(echo "${response}" | sed '$d')
    if [[ ${status_code} -ne 200 ]] ; then
      die "Error logging in: ${status_code} / ${json}"
    fi
    echo "${json}" > ${SESSION_JSON}
  fi

}

function get_session_name {
  echo -n "$(cat ${SESSION_JSON} 2> /dev/null | grep -m 1 '\"name\"' | awk -F '"' '{print $4}' | tr -d ' \n')"
}
function get_session_email {
  echo -n "$(cat ${SESSION_JSON} 2> /dev/null | grep -m 1 '\"email\"' | awk -F '"' '{print $4}' | tr -d ' \n')"
}

if [[ ! -f ${SESSION_JSON} && $(basename $0) != "wl_sign_up" && $(basename $0) != "wl_whoami" ]] ; then
  wl_auth "${__no_value__}" "Y"
#else
#  echo "not signing in (already have session, or command that does not require session)..."
fi

if [ -f "${SESSION_JSON}" ] ; then
  SESSION_TOKEN="${WL_API_KEY}: $(cat ${SESSION_JSON} 2> /dev/null | grep apiToken | awk -F '"' '{print $4}')"
fi
