#!/bin/bash

SCRIPT="${0}"
SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
. ${SCRIPT_DIR}/_wl_common

ROOM_NAME="${1:?$(translate_message err_room_required)}"
WEBSOCKET_PID="${2:?$(translate_message err_websocket_wl_play_pid_required)}"

ACTIVE_CHAR=""
ACTIVE_CHAR_INDEX=1
ACTIVE_TRAY_INDEX=1
TILES=()
LETTERS=()
INDEXES=()
WS_MARKER_FILE="${WS_MARKER_FILE_DIR}/$$"

function show_help {
  HELP_FILE="${SCRIPT_DIR}/lang/help.$(lang).md"
  if [[ ! -f ${HELP_FILE} ]] ; then
    HELP_FILE="${SCRIPT_DIR}/lang/help.en.md"
  fi
  if [[ ! -f ${HELP_FILE} ]] ; then
    error "$(translate_message err_help_notFound): ${HELP_FILE}"
  else
    cat ${HELP_FILE}
  fi
}

function reset_play {
  unset TILES
  TILES=()
  unset LETTERS
  LETTERS=()
  unset INDEXES
  INDEXES=()
  ACTIVE_CHAR=""
  ACTIVE_CHAR_INDEX=1
  ACTIVE_TRAY_INDEX=1
}

function current_word {
  for c in "${LETTERS[@]}" ; do
    echo -n "${c}" | tr '[:lower:]' '[:upper:]'
  done
}
function current_word_length {
  echo -n $(current_word) | wc -c | tr -d ' '
}

function subtract_letter {
  if [[ -z "$(current_word)" ]] ; then
    return
  fi

  LETTER_INDEX=$(expr ${ACTIVE_TRAY_INDEX} - 1)
  if [[ ${LETTER_INDEX} -lt 0 ]] ; then
    # should never happen
    return
  fi
  ACTIVE_TRAY_INDEX=${LETTER_INDEX}
  if [[ ${ACTIVE_TRAY_INDEX} -le 0 ]] ; then
    ACTIVE_TRAY_INDEX=1
  fi

  echo "start subtract_letter: letters=${LETTERS[@]} / LETTER_INDEX=${LETTER_INDEX}, ACTIVE_TRAY_INDEX=${ACTIVE_TRAY_INDEX}" >> /tmp/plog

  unset 'TILES[${LETTER_INDEX}]'
  unset 'LETTERS[${LETTER_INDEX}]'
  unset 'INDEXES[${LETTER_INDEX}]'
  TILES=( "${TILES[@]:0:${LETTER_INDEX}}" "${TILES[@]:${ACTIVE_TRAY_INDEX}}" )
  LETTERS=( "${LETTERS[@]:0:${LETTER_INDEX}}" "${LETTERS[@]:${ACTIVE_TRAY_INDEX}}" )
  INDEXES=( "${INDEXES[@]:0:${LETTER_INDEX}}" "${INDEXES[@]:${ACTIVE_TRAY_INDEX}}" )

#  ACTIVE_CHAR="$(echo $(current_word) | head -c $(expr ${ACTIVE_CHAR_INDEX} + 1) | tail -c 1)"
  ACTIVE_CHAR="${LETTERS[${LETTER_INDEX}]}"
  ACTIVE_CHAR_INDEX="${INDEXES[${LETTER_INDEX}]}"
  echo "end subtract_letter: letters=${LETTERS[@]} / LETTER_INDEX=${LETTER_INDEX}, ACTIVE_TRAY_INDEX=${ACTIVE_TRAY_INDEX}, AC=${ACTIVE_CHAR}, should be ${LETTERS[${LETTER_INDEX}]}, L0=${LETTERS[0]}, L1=${LETTERS[1]}, L2=${LETTERS[2]}" >> /tmp/plog
}

function play_obj {
  if [[ ! -z ${CURRENT_PLAY} && ${#LETTERS[@]} -gt 0 ]] ; then
    cat <<EOF
  {
    "room": "${ROOM_NAME}",
    "stateChange": "word_played",
    "id": "$(session_player)",
    "clientId": "$(session_player)",
    "apiToken": "$(session_apiToken)",
    "word": "$(current_word)",
    "tiles": ${CURRENT_PLAY}
  }
EOF
  else
    error "no valid word to play"
  fi
}

X1=$(cat ${WL_DIR}/rooms/${ROOM_NAME}/x1)
Y1=$(cat ${WL_DIR}/rooms/${ROOM_NAME}/y1)
VIEW_SIZE=$(cat ${WL_DIR}/rooms/${ROOM_NAME}/view_size)
ROOM_PALETTE=${WL_DIR}/rooms/${ROOM_NAME}/palette.json
BOARD_JSON=${WL_DIR}/rooms/${ROOM_NAME}/board.json
PLAY_JSON=${WL_DIR}/rooms/${ROOM_NAME}/play.json

BOARD_REQUEST_PREFIX="{ \"palette\": "
BOARD_REQUEST_TILES_JSON_PREFIX=", \"tiles\": [ "
BOARD_REQUEST_TILES_JSON_SEP=", "
BOARD_REQUEST_JSON_SUFFIX=" ] }"

function board_preview_obj {
  echo -n "${BOARD_REQUEST_PREFIX}"
  if [[ -f ${ROOM_PALETTE} && $(cat ${ROOM_PALETTE} | tr -d ' \n' | wc -c | tr -d ' ') -gt 0 ]] ; then
    cat ${ROOM_PALETTE}
  else
    echo -n "null"
  fi
  echo -n "${BOARD_REQUEST_TILES_JSON_PREFIX}"
  first=1
  for tile in "${TILES[@]}" ; do
    if [[ "${tile}" =~ /null/ ]] ; then
      break
    fi
    if [[ -z "$(echo -n ${tile} | tr -d ' ')" ]] ; then
      continue
    fi
    if [ ${first} -ne 1 ] ; then
      echo -n "${BOARD_REQUEST_TILES_JSON_SEP}"
    fi
    echo -n " { ${tile} }"
    first=0
  done
  echo -n "${BOARD_REQUEST_JSON_SUFFIX}"
}

function save_palette {
  PALETTE="$(json_node "$(cat ${BOARD_JSON})" palette)"
  if [[ ! -z "${PALETTE}" ]] ; then
    echo "${PALETTE}" > ${ROOM_PALETTE}
  fi
}

function show_rooms {
  rooms_json=$(wl_get ${WL_API}/me/rooms)
  i=1
  #echo "${rooms_json}" >> /tmp/rooms.json
  for room in $(echo "${rooms_json}" | jq '.[] | .name' | tr -d '"') ; do
    roomState=$(json_find "${rooms_json}" name "${room}" roomState)
    echo "${i} - ${room} - $(translate_message msg_room_state_${roomState})"
    i=$(expr ${i} + 1)
  done
  echo "n - New Game"
  echo "q - Back to Current Game"
  echo ; echo -n "$(room_prompt)"
  while IFS= read line 2> /dev/null ; do
    if [[ ! -z "${line}" ]] ; then
      case ${line} in
        q|Q)
          return
        ;;
        n|N)
          echo ; echo ; exec ${SCRIPT_DIR}/wl_rooms
        ;;
        (*[!0-9]*)
          echo ; echo -n "$(room_prompt)"
          continue
        ;;
        *)
          # all digits, must be room number
          line=$(echo "${line}" | tr -d ' \n')
          if [[ -z "${line}" ]] ; then
            break
          fi
          roomName=$(echo "${rooms_json}" | jq '.['$(expr ${line} - 1)'] | .name' | tr -d '"')
          if [[ $(wl_exists "${WL_API}/rooms/${roomName}") == "true" ]] ; then
            exec ${SCRIPT_DIR}/wl_join "${roomName}"
          else
            error "$(translate_message err_room_notFound)"
          fi
        ;;
      esac
    fi
    echo ; echo -n "$(room_prompt)"
  done
  echo "end of script" >> /tmp/roomlog
}

function show_tray {
  echo
  if [[ -z "$(current_word)" ]] ; then
    echo "   [  (empty)  ]"
    echo
  else
    echo "   [  $(current_word)  ]"
    echo -n "     "
    i=0
    while [[ ${i} -lt ${ACTIVE_TRAY_INDEX} ]] ; do
      echo -n " "
      i=$(expr ${i} + 1)
    done
    echo "^"
  fi
}

function show_board {
  if [[ -f ${BOARD_JSON} ]] ; then
    cp ${BOARD_JSON} ${BOARD_JSON}.bak
  fi
  echo "$(board_preview_obj)" | grep tiles >> /tmp/plog
  board_status="$(wl_post "${WL_API}/rooms/${ROOM_NAME}/board/preview.txt?x1=${X1}&x2=$(expr ${X1} + ${VIEW_SIZE})&y1=${Y1}&y2=$(expr ${Y1} + ${VIEW_SIZE})" "$(board_preview_obj)" "${BOARD_JSON}")" \
    || die "$(translate_message err_api_boardView)"
  case $(http_code ${board_status}) in
    200)
      board="$(json_node "$(cat ${BOARD_JSON})" grid)"
      if [[ ! -z "${board}" ]] ; then
        save_palette
        echo
        printf "$(printf "${board}" | tr -d '"')"
      fi
    ;;
    422)
      error "$(validation_errors "${BOARD_JSON}")"
      if [[ -f ${BOARD_JSON}.bak ]] ; then
        cp ${BOARD_JSON}.bak ${BOARD_JSON}
      fi
    ;;
    *)
      die "$(translate_message err_api_boardView)"
    ;;
  esac

  if [[ ${#TILES[*]} -gt 0 ]] ; then
    SUCCESS="$(json_val "$(cat ${BOARD_JSON})" success)"
    if [[ -z "${SUCCESS}" || "${SUCCESS}" != "true" ]] ; then
      error -n "$(translate_message 'err_game_invalidPlay'): $(current_word)"
      CURRENT_PLAY=""
      subtract_letter
    else
      CURRENT_PLAY="$(json_node "$(cat ${BOARD_JSON})" playedTiles)"
    fi
  fi
}

function fresh_board_view {
  show_board ; echo ; show_tray
  echo -n "$(wl_prompt)"
}

function async_fresh_board_view {
  echo ; echo ; echo "<?~~~ !! async update !! ~~~~?>"; fresh_board_view
}

fresh_board_view

while [ 1 ] ; do
 while IFS= read -s -r -t 2 -n1 char 2> /dev/null ; do
  reset=0
  case ${char} in
    # Add a letter to the tray
    [a-zA-z])
      ACTIVE_CHAR="${char}"
      ACTIVE_CHAR_INDEX=1
      for c in "${LETTERS[@]}" ; do
        if [[ ${c} == ${char} ]] ; then
          ACTIVE_CHAR_INDEX=$(expr ${ACTIVE_CHAR_INDEX} + 1)
        fi
      done
      TILES+=("\"symbol\": \"${char}\", \"index\": ${ACTIVE_CHAR_INDEX}")
      LETTERS+=("${char}")
      INDEXES+=(${ACTIVE_CHAR_INDEX})
      ACTIVE_TRAY_INDEX=$(current_word_length)
    ;;

    # Increment current active char index
    '>')
      echo "> start: AC=${ACTIVE_CHAR}, ACI=${ACTIVE_CHAR_INDEX}, #TILES[@]=${#TILES[@]}" >> /tmp/plog
      if [[ ${#TILES[@]} -gt 0 ]] ; then
        ACTIVE_CHAR_INDEX=$(expr ${ACTIVE_CHAR_INDEX} + 1)
        TILES[${ACTIVE_TRAY_INDEX}]="\"symbol\": \"${LETTERS[${ACTIVE_TRAY_INDEX}-1]}\", \"index\": ${ACTIVE_CHAR_INDEX}"
        INDEXES[${ACTIVE_TRAY_INDEX}]=${ACTIVE_CHAR_INDEX}
        echo "> end: BPO: $(board_preview_obj)" | grep tiles >> /tmp/plog
      else
        continue
      fi
    ;;

    # Decrement current active char index, if possible
    '<')
      echo "< start: AC=${ACTIVE_CHAR}, ACI=${ACTIVE_CHAR_INDEX}" >> /tmp/plog
      if [[ ${#TILES[@]} -gt 0 ]] ; then
        ACTIVE_CHAR_INDEX=$(expr ${ACTIVE_CHAR_INDEX} - 1)
        if [ ${ACTIVE_CHAR_INDEX} -lt 1 ] ; then
          ACTIVE_CHAR_INDEX=1
        fi
        TILES[${ACTIVE_TRAY_INDEX}]="\"symbol\": \"${LETTERS[${ACTIVE_TRAY_INDEX}]}\", \"index\": ${ACTIVE_CHAR_INDEX}"
        INDEXES[${ACTIVE_TRAY_INDEX}]=${ACTIVE_CHAR_INDEX}
        echo "< end: BPO: $(board_preview_obj)" | grep tiles >> /tmp/plog
      else
        continue
      fi
    ;;

    # Move current letter to the right in the tray, if possible
    ']')
      if [[ ${#TILES[@]} -gt 1 && ${ACTIVE_TRAY_INDEX} -lt $(current_word_length) ]] ; then
        ATR_INDEX=$(expr ${ACTIVE_TRAY_INDEX} - 1)
        next=$(expr ${ATR_INDEX} + 1)
        SAVED_TILE="${TILES[${next}]}"
        SAVED_LETTER="${LETTERS[${next}]}"
        SAVED_INDEX="${INDEXES[${next}]}"
        TILES[${next}]="${TILES[${ATR_INDEX}]}"
        LETTERS[${next}]="${LETTERS[${ATR_INDEX}]}"
        INDEXES[${next}]="${INDEXES[${ATR_INDEX}]}"
        TILES[${ATR_INDEX}]="${SAVED_TILE}"
        LETTERS[${ATR_INDEX}]="${SAVED_LETTER}"
        INDEXES[${ATR_INDEX}]="${SAVED_INDEX}"
        ACTIVE_TRAY_INDEX=$(expr ${ACTIVE_TRAY_INDEX} + 1)
      else
        continue
      fi
    ;;

    # Move current letter to the left in the tray, if possible
    '[')
      if [[ ${#TILES[@]} -gt 1 && ${ACTIVE_TRAY_INDEX} -gt 1 ]] ; then
        ATR_INDEX=$(expr ${ACTIVE_TRAY_INDEX} - 1)
        prev=$(expr ${ATR_INDEX} - 1)
        SAVED_TILE="${TILES[${prev}]}"
        SAVED_LETTER="${LETTERS[${prev}]}"
        SAVED_INDEX="${INDEXES[${prev}]}"
        TILES[${prev}]="${TILES[${ATR_INDEX}]}"
        LETTERS[${prev}]="${LETTERS[${ATR_INDEX}]}"
        INDEXES[${prev}]="${INDEXES[${ATR_INDEX}]}"
        TILES[${ATR_INDEX}]="${SAVED_TILE}"
        LETTERS[${ATR_INDEX}]="${SAVED_LETTER}"
        INDEXES[${ATR_INDEX}]="${SAVED_INDEX}"
        ACTIVE_TRAY_INDEX=$(expr ${ACTIVE_TRAY_INDEX} - 1)
      else
        continue
      fi
    ;;

    # Change currently active letter in the tray to the right, if possible
    '}')
      if [[ ${#TILES[@]} -gt 1 && ${ACTIVE_TRAY_INDEX} -lt $(current_word_length) ]] ; then
        ATR_INDEX=$(expr ${ACTIVE_TRAY_INDEX})
        next=$(expr ${ATR_INDEX} + 1)
        ACTIVE_TRAY_INDEX=${next}
        ACTIVE_CHAR="${LETTERS[${ATR_INDEX}]}"
        ACTIVE_CHAR_INDEX="${INDEXES[${ATR_INDEX}]}"
      else
        continue
      fi
    ;;

    # Change currently active letter in the tray to the left, if possible
    '{')
      if [[ ${#TILES[@]} -gt 1 && ${ACTIVE_TRAY_INDEX} -gt 1 ]] ; then
        ATR_INDEX=$(expr ${ACTIVE_TRAY_INDEX} - 1)
        prev=$(expr ${ATR_INDEX} - 1)
        ACTIVE_TRAY_INDEX=${ATR_INDEX}
        ACTIVE_CHAR="${LETTERS[${prev}]}"
        ACTIVE_CHAR_INDEX="${INDEXES[${prev}]}"
      else
        continue
      fi
    ;;

    # Submit the letters in the tray as our play, if there are any
    '')
      if [[ -z "${CURRENT_PLAY}" ]] ; then
        error "$(translate_message err_game_noCurrentPlay)"
      else
        play_status="$(wl_post "${WL_API}/rooms/${ROOM_NAME}/play" "$(play_obj)" "${PLAY_JSON}" "200 422")"
        case $(http_code ${play_status}) in
          200)
            reset_play
            reset=1
            play_output=""
          ;;
          422)
            play_output="$(validation_errors "$(cat "${PLAY_JSON}")")"
          ;;
          *)
            play_output="$(translate_message err_api_play)"
          ;;
        esac
      fi
    ;;

    # Remove the most recently added letter from the tray
    '-')
      subtract_letter
    ;;

    # Clear the tray
    ' ')
      echo ; echo "$(translate_message msg_word_reset)"
      reset_play
      reset=1
    ;;

    '?')
      show_help
    ;;

    '/')
      echo ; echo
      show_rooms
    ;;

    # Didn't understand that, skip it
    *)
      continue
    ;;
  esac

  # Get the board preview
  if [[ ${reset} -eq 1 ]] ; then
    reset=0
  fi
  show_board

  # If the play resulted in a message to the user, show that here
  if [[ ! -z "${play_output}" ]] ; then
    error -n "${play_output}"
    play_output=""
  fi

  # Show the tray
  echo
  show_tray

  echo -n "$(wl_prompt)"

 done

 if [[ -f ${WS_MARKER_FILE} ]] ; then
   rm ${WS_MARKER_FILE}
   async_fresh_board_view
 fi
done
