#!/bin/bash

SCRIPT="${0}"
SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
. ${SCRIPT_DIR}/_wl_common

ROOM_NAME="${1:?no room name specified}"
PLAYER_NAME="${2:?no player name specified}"

function join_obj () {
  cat <<EOF
  {
    "name":"${PLAYER_NAME}"
  }
EOF
}

ROOM_DIR="${WL_DIR}/rooms/${ROOM_NAME}"
mkdir -p ${ROOM_DIR}
curl --header "Content-Type: application/json" -X POST -d "$(join_obj)" ${WL_API}/rooms/${ROOM_NAME}/join > ${ROOM_DIR}/player.json \
  || die "error joining game"

echo "${ROOM_NAME}" > ${WL_DIR}/current_room
echo "0" > ${ROOM_DIR}/x1
echo "0" > ${ROOM_DIR}/y1
echo "10" > ${ROOM_DIR}/view_size

# show board
${SCRIPT_DIR}/board
