#!/bin/bash

SCRIPT="${0}"
SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
. ${SCRIPT_DIR}/_wl_common

ROOM_NAME="${1:?$(translate_message err_room_required)}"
PLAYER_NAME="${2-$(session_name)}"

function join_obj {
  cat <<EOF
  {
    "clientId": "$(session_player)",
    "name":"${PLAYER_NAME}"
  }
EOF
}

TEMP_SESSION=$(mktemp /tmp/wl_room_session.XXXXXXXX.json)
join_status=$(wl_post "${WL_API}/rooms/${ROOM_NAME}/join" "$(join_obj)" "${TEMP_SESSION}" "200 422")
case $(http_code ${join_status}) in
  200)
  ;;
  422)
    die "$(validation_errors "$(cat ${TEMP_SESSION})")"
  ;;
  *)
    die "$(translate_message err_api_join)"
  ;;
esac
if [[ ! -f ${TEMP_SESSION} || ! -s ${TEMP_SESSION} ]] ; then
  die "$(translate_message err_api_join)"
fi

ROOM_NAME="$(json_val "$(cat ${TEMP_SESSION})" room)"
if [[ -z "${ROOM_NAME}" ]] ; then
  die "$(translate_message err_api_join): $(cat ${TEMP_SESSION})"
fi

ROOM_DIR="${WL_DIR}/rooms/${ROOM_NAME}"
mkdir -p ${ROOM_DIR}

if [[ -z "${CURRENT_ROOM}" ]] ; then
  die "$(translate_message err_room_noCurrentRoom)"
fi

echo "${ROOM_NAME}" > ${CURRENT_ROOM}
cp ${TEMP_SESSION} ${CURRENT_ROOM}.json
cp ${TEMP_SESSION} ${ROOM_DIR}/room.json
echo "0" > ${ROOM_DIR}/x1
echo "0" > ${ROOM_DIR}/y1
echo "10" > ${ROOM_DIR}/view_size

# show board, play game
exec ${SCRIPT_DIR}/wl_play "${ROOM_NAME}" -n
