#!/bin/bash

SCRIPT="${0}"
SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
. ${SCRIPT_DIR}/_wl_common

ROOM_NAME="${1:?no room name specified}"
PLAYER_NAME="${2-$(get_session_name)}"

function join_obj () {
  cat <<EOF
  {
    "name":"${PLAYER_NAME}"
  }
EOF
}

TEMP_SESSION=$(mktemp /tmp/wl_room_session.XXXXXXXX.json)
wl_post "${SESSION_TOKEN}" ${WL_API}/rooms/${ROOM_NAME}/join "$(join_obj)" ${TEMP_SESSION} || die "error joining game"
if [[ ! -f ${TEMP_SESSION} || ! -s ${TEMP_SESSION} ]] ; then
  die "error joining game"
fi

ROOM_NAME="$(cat ${TEMP_SESSION} | grep -m 1 '"room"' | awk -F '"' '{print $4}')"
ROOM_DIR="${WL_DIR}/rooms/${ROOM_NAME}"
mkdir -p ${ROOM_DIR}

if [[ -z "${CURRENT_ROOM}" ]] ; then
  die "No CURRENT_ROOM defined, should have been defined by _wl_base"
fi

echo "${ROOM_NAME}" > ${CURRENT_ROOM}
cp ${TEMP_SESSION} ${CURRENT_ROOM}.json
cp ${TEMP_SESSION} ${ROOM_DIR}/room.json
echo "0" > ${ROOM_DIR}/x1
echo "0" > ${ROOM_DIR}/y1
echo "10" > ${ROOM_DIR}/view_size

# show board
${SCRIPT_DIR}/wl_board ${ROOM_NAME}
