#!/bin/bash

SCRIPT="${0}"
SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
. ${SCRIPT_DIR}/_wl_root

MODEL="${1:?$(translate_message err_model_required)}"

wl_post "${SESSION_TOKEN}" "${WL_API}/entityConfigs/populate/${MODEL}"
