#!/bin/bash

SCRIPT="${0}"
SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
. ${SCRIPT_DIR}/_wl_common

ROOM_NAME="${1}"
if [[ -z "${ROOM_NAME}" ]] ; then
  ROOM_NAME="$(current_room)"
  if [[ -z "${ROOM_NAME}" ]] ; then
    error "$(translate_message err_room_noCurrentRoom)"
    exec ${SCRIPT_DIR}/wl_rooms
  fi
fi

NO_JOIN="${2}"
if [[ -z ${NO_JOIN} || "${NO_JOIN}" != "-n" ]] ; then
  exec ${SCRIPT_DIR}/wl_join ${ROOM_NAME}
fi

WL_PLAY_PID="$$"
WEBSOCKET_PID="${3}"
if [[ -z ${WEBSOCKET_PID} ]] ; then
  set -e
  ${SCRIPT_DIR}/_wl_websocket ${WL_PLAY_PID} &
  WEBSOCKET_PID=$!
  disown %1
  exec ${0} ${ROOM_NAME} -n ${WEBSOCKET_PID}
fi

function shutdown_websocket {
  if [[ $(ps uxw | grep ${WEBSOCKET_PID} | grep _wl_websocket | grep -v grep | wc -l | tr -d ' ') -gt 0 ]] ; then
    kill -TERM ${WEBSOCKET_PID} 2> /dev/null || error "$(translate_message err_websocket_shutdown)"
    kill -9 ${WEBSOCKET_PID} 2> /dev/null
  fi
  stty sane ; echo
  bash -i ${0} ${ROOM_NAME} &
  exit 0
}
trap 'shutdown_websocket' INT TERM EXIT

exec ${SCRIPT_DIR}/_wl_play ${ROOM_NAME} ${WEBSOCKET_PID}
