#!/bin/bash

SCRIPT="${0}"
SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
. ${SCRIPT_DIR}/_wl_common

VERBOSE="${1}"
if [[ ! -z "${VERBOSE}" && "${VERBOSE}" == "-v" ]] ; then
  VERBOSE=1
  shift
else
  VERBOSE=0
fi
ROOM="${1}"

if [[ -z "${ROOM}" ]] ; then
  if [[ ${VERBOSE} -eq 1 ]] ; then
    wl_get "${SESSION_TOKEN}" ${WL_API}/rooms
    exit $?
  fi

  echo "Available rooms:"
  IFS=$'\n'
  for room in $(wl_get "${SESSION_TOKEN}" ${WL_API}/rooms | jq .[].name) ; do
    echo "  * ${room}"
  done
  echo

else
  if [[ ${VERBOSE} -eq 1 ]] ; then
    wl_get "${SESSION_TOKEN}" ${WL_API}/rooms/${ROOM}
    exit $?
  fi

  room=$(wl_get "${SESSION_TOKEN}" ${WL_API}/rooms/${ROOM})

  echo "Details for ${ROOM}"
  board=$(json_val "${room}" settings.board.name)
  width=$(json_val "${room}" settings.board.settings.width)
  length=$(json_val "${room}" settings.board.settings.length)
  maxPlayers=$(json_val "${room}" settings.maxPlayers)

  if [[ -z "${width}" ]] ; then
    width="infinite"
  fi
  if [[ -z "${length}" ]] ; then
    length="infinite"
  fi

  if [[ ! -z "${board}" ]] ; then
    echo "  Board name:       ${board}"
  fi
  echo "  Board dimensions: ${width} x ${length}"
  if [[ ! -z "${maxPlayers}" ]] ; then
    echo "  Max players:      ${maxPlayers}"
  fi
fi
