#!/bin/bash

SCRIPT="${0}"
SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
. ${SCRIPT_DIR}/_wl_common

HAS_ACCOUNT=$(cat ${SESSION_JSON} | awk -F '"' '{print $2}' | grep ^account$ | wc -l | tr -d ' ')
if [[ -z "${HAS_ACCOUNT}" ]] ; then
  die "error determining account status"
fi

if [[ ${HAS_ACCOUNT} -eq 1 ]] ; then
  echo "account successfully signed up and logged in as $(get_session_email)"
else
  NAME="$(cat ${SESSION_JSON} | grep -m 1 name | awk -F '"' '{print $4}' | tr -d ' \n')"
  sign_up "${NAME}" "N"
  echo "Successfully signed up and logged in as $(get_session_name)"
fi
