#!/bin/bash

SCRIPT="${0}"
SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
. ${SCRIPT_DIR}/_wl_common

HAS_ACCOUNT=$(cat ${SESSION_JSON} 2> /dev/null | awk -F '"' '{print $2}' | grep ^account$ | wc -l | tr -d ' ')
if [[ -z "${HAS_ACCOUNT}" ]] ; then
  die "$(translate_message err.api.checkingSession)"
fi

if [[ ${HAS_ACCOUNT} -eq 1 ]] ; then
  echo "$(translate_message msg.signin.success) $(session_email)"
else
  NAME="$(cat ${SESSION_JSON} 2> /dev/null | grep -m 1 name | awk -F '"' '{print $4}' | tr -d ' \n')"
  wl_auth "${NAME}" "N"
  echo ""
  echo "$(translate_message msg.signup.success) $(session_name)"
  echo ""
fi
