#!/bin/bash

SCRIPT="${0}"
SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
. ${SCRIPT_DIR}/_wl_common

if [[ ! -f ${SESSION_JSON} ]] ; then
  die "not signed in"
fi

name="$(get_session_email)"
if [[ -z "${name}" ]] ; then
  name="$(get_session_name) (anonymous user)"
fi

wl_get "${SESSION_TOKEN}" ${WL_API}/auth/logout
rm -f ${SESSION_JSON}
echo "signed out as ${name}"
