#!/bin/bash

SCRIPT="${0}"
SCRIPT_DIR=$(cd $(dirname ${SCRIPT}) && pwd)
. ${SCRIPT_DIR}/_wl_common

if [[ ! -f ${SESSION_JSON} ]] ; then
  error "$(translate_message msg.notLoggedIn)"
  exit 1
fi

email="$(session_email)"
if [[ ! -z "${email}" ]] ; then
  echo "$(translate_message msg.signin.success) ${email}"
  exit 0
fi

name="$(session_name)"
if [[ ! -z "${name}" ]] ; then
  echo "$(translate_message msg.signin.success) ${name} $(translate_message msg.user.anonymousFlag)"
  exit 0
fi

die "$(translate_message err.userUnknown_sessionDump): $(cat ${SESSION_JSON})"
